### ISSUE TITLE
Trajectory Analysis Bug?

### ISSUE THREAD

**Issue by gasilva** [icinganalysis/icinganalysis.github.io#1]
```
parallels@ubuntu-linux-20-04-desktop:~/icinganalysis.github.io/icinganalysis/calculate_drop_trajectory$ python naca_tn_3024.py 
  File "naca_tn_3024.py", line 256
    plt.suptitle(f"Phi=1000, K=0.125")
                                    ^
SyntaxError: invalid syntax
```

```
culate_drop_trajectory$ python3.8 naca_tn_3024.py 
Traceback (most recent call last):
  File "naca_tn_3024.py", line 1, in <module>
    from icinganalysis.air_properties import calc_pressure, CP_AIR, GAMMA_AIR, R_AIR
ModuleNotFoundError: No module named 'icinganalysis'
```

```
culate_drop_trajectory$ python2.7 naca_tn_3024.py 
  File "naca_tn_3024.py", line 256
    plt.suptitle(f"Phi=1000, K=0.125")
                                    ^
SyntaxError: invalid syntax
```

Do you know how to fix those errors?

**Comment by icinganalysis** [comment]
Thanks for the report.

For the ModuleNotFoundError, the directory icinganalysis must be in the pythonpath to be recognized as a module.

For the invalid syntax, you appear to be using python 2.7
The code was written with python 3.7, which includes "f" format syntax.

https://icinganalysis.github.io/python-coding-style-guide.html

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by gasilva** [comment]
Thank you for your attention and quick response.

I have Python 3.8 and Python 2.7 installed.
Please check the command that I ran in different versions of Python. This is not a problem for me. But the code gives different messages when running each one. I do no know which version of Python you used.

There is no readme explaining how to install the module and how to run the codes. I am just guessing.

`No module named 'icinganalysis'`
is it available through pip install?

and the other errors appear to be syntax or run-time errors...

Please explain how to run the collection efficiency from scratch after git cloning the repo?
sorry to be insistent...but I would like to run the codes, and I could not find instructions.

**Comment by icinganalysis** [comment]
I updated the README.md with instructions.

Please let me know if it works for you.
("It worked on my machine.")

Also note that the repository has been recently updated,
so update your local copy.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by gasilva** [comment]
I appreciate it very much! Have a nice weekend.
